language: node_js

node_js:
  - '8.9.4'

branches:
  only:
    - master
install:

  - npm install

before_script:
  - npm run build

after_success:
  - firebase use app
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
