language: node_js

node_js:
  - '6.11.0'

branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm install

before_script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
